[package]
name = "aequi"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
aequi-core = { path = "../core" }
aequi-storage = { path = "../storage" }
tauri = { version = "2", features = ["devtools"] }
serde.workspace = true
serde_json = "1.0"
tokio.workspace = true
