[package]
name = "aequi-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
rust_decimal.workspace = true
chrono.workspace = true
serde.workspace = true
thiserror.workspace = true
